macOS support for running individual generators
The workarounds in `setup.py` to install `ruamel.yaml` and `marko` don't
work when starting from a clean build, e.g.:

```sh
make clean
git clean -dfx
make preinstallation
make install_test
make pyspec
make -j gen_fork_choice
```

This results in error:

```
generator fork_choice started
Processing /consensus-specs
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /consensus-specs/tests/generators/fork_choice/venv/bin/python3.11: No module named pip
      Traceback (most recent call last):
        File "<string>", line 45, in <module>
      ModuleNotFoundError: No module named 'ruamel'
```

Adding `--no-use-pep517` disables some environment isolation for `pip`,
and makes this work once more on macOS. `--no-use-pep517` requires prior
installation of `setuptools` and `wheel`.

```
% sw_vers
ProductName:      macOS
ProductVersion:   14.2.1
BuildVersion:     23C71
```